//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecensionsProjekt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToReview
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ReviewId { get; set; }
        public bool HasLiked { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
    }
}
